version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "feeling-lucky"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1o931l0m2ej6a"
s3_prefix = "feeling-lucky"
disable_rollback = true
parameter_overrides = "AppName=\"feeling-lucky\""

